Add firewall dependency for gitea/nexus
microsoft/AzureTRE pull request #1298
Opened 2022-02-14 11:21 UTC by stuartleeks

Add dependency on `firewall` module to `gitea` and `nexus` modules to fix #1297

2022-02-14 11:44 UTC, tamirkamara commented
@stuartleeks perhaps it would be nice to add the dependency for Gitea too?

2022-02-14 11:45 UTC, martinpeck approved these changes
LGTM

2022-02-14 11:46 UTC, martinpeck commented
> @stuartleeks perhaps it would be nice to add the dependency for Gitea too?

how do you mean @tamirkamara ?

2022-02-14 11:51 UTC, stuartleeks commented
> @stuartleeks perhaps it would be nice to add the dependency for Gitea too?

@tamirkamara  - do you mean something other than this?

![image](https://user-images.githubusercontent.com/1824461/153859214-15d01ccf-073b-4a64-b051-fb4e26e9b35f.png)

https://github.com/microsoft/AzureTRE/blob/caab6bd33aa4c52acc7844f318cfc694647ffe25/templates/core/terraform/main.tf#L133

2022-02-14 13:35 UTC, tamirkamara approved these changes
I probably missed that line about gitea (not sure how).

2022-02-16 13:22 UTC, ross-p-smith commented on .github/workflows/deploy_tre_reusable.yml
> +  debug:
Assuming that this is not related to this PR?

2022-02-16 13:23 UTC, ross-p-smith commented on .github/workflows/deploy_tre.yml
> +    # branches: [main]
Assuming test

2022-02-16 13:23 UTC, ross-p-smith requested changes
Assuming you are using this for debugging something

2022-02-17 10:43 UTC, stuartleeks commented
Closing and re-opening to test whether the build issue is transient or not

2022-02-17 10:43 UTC, closed without merging