Airlock - API - approve/reject a request
microsoft/AzureTRE pull request #2044
Opened 2022-06-15 14:13 UTC by anatbal

# PR fixes issue #1840

## What is being addressed
** testing will be addressed in a subsequential pr**
- Implement the review endpoint which allows the user to approve/reject a request
- Create a new object - an airlock review
- Fixed exception to return 400 whenever validation fails
- Since status is not an attribute of airlock review, renamed it and changed the history mechanism so it will be included only on airlock requests
- Fix minor typos

2022-06-15 16:15 UTC, eladiw requested changes
some minor changes

2022-06-15 16:15 UTC, eladiw commented on api_app/api/routes/airlock.py
> +        logging.error(f"Failed create airlock request model instance: {e}")
```suggestion
        logging.error(f"Failed creating airlock request model instance: {e}")
```

2022-06-15 16:15 UTC, eladiw commented on api_app/api/routes/airlock.py
> +async def create_airlock_review(airlock_review_input: AirlockReviewInCreate, airlock_request=Depends(get_airlock_request_by_id_from_path), user=Depends(get_current_workspace_owner_or_researcher_user)
correct, I think it should be only the ws owner

2022-06-15 16:15 UTC, eladiw commented on api_app/api/routes/airlock.py
> +        logging.error(f"Failed create airlock review model instance: {e}")
```suggestion
        logging.error(f"Failed creating airlock review model instance: {e}")
```

2022-06-15 16:15 UTC, eladiw commented on api_app/api/routes/airlock.py
> +    await save_airlock_review(airlock_review, airlock_review_repo, user)
dont you want to first save the review.
imagine the saving of the review object fails, so in the current code, you already continued the flow, and the review is not saved == cant trace back.

prefer to save the review first, worst case the flow fails later, but it didnt continue until the trigger was saved

wdyt

2022-06-15 16:15 UTC, eladiw commented on api_app/event_grid/helpers.py
> +    workspace_id = airlock_request.workspaceId[-4:]
```suggestion
    short_workspace_id = airlock_request.workspaceId[-4:]
```

2022-06-15 16:27 UTC, anatbal commented on api_app/api/routes/airlock.py
> +async def create_airlock_review(airlock_review_input: AirlockReviewInCreate, airlock_request=Depends(get_airlock_request_by_id_from_path), user=Depends(get_current_workspace_owner_or_researcher_user)
Fixed

2022-06-15 16:27 UTC, anatbal commented on api_app/api/routes/airlock.py
> +        logging.error(f"Failed create airlock request model instance: {e}")
Fixed

2022-06-15 16:28 UTC, anatbal commented on api_app/api/routes/airlock.py
> +        logging.error(f"Failed create airlock review model instance: {e}")
Fixed

2022-06-15 16:28 UTC, anatbal commented on api_app/event_grid/helpers.py
> +    workspace_id = airlock_request.workspaceId[-4:]
Fixed

2022-06-15 16:30 UTC, anatbal commented
/test-extended

2022-06-15 16:34 UTC, anatbal commented
/test-extended

2022-06-15 18:49 UTC, anatbal commented
/test-destroy-env

2022-06-16 17:34 UTC, eladiw commented
/test-destroy-env

2022-06-16 18:27 UTC, anatbal commented
/test-extended

2022-06-16 18:41 UTC, eladiw commented
/test-extended

2022-06-16 19:34 UTC, merged