Updates to all porter bundles to build docker images for amd64 platform from arm64 machines locally
microsoft/AzureTRE pull request #3827
Opened 2024-01-16 14:49 UTC by m1p1h

This update fixes #3823 

## What is being addressed

Porter bundles built on arm64 machines locally currently generate docker images for arm64 platforms. 

## How is this addressed

- Specifies amd64 platform in porter docker template files
- Identifies underlying architecture of dev machine running docker and specifies amd64 platform when building runtime images of a bundle

2024-01-16 14:57 UTC, m1p1h commented
> @m1p1h please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="NHS"]

2024-01-16 14:58 UTC, m1p1h commented
> @m1p1h the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree company="nhs"

2024-01-16 15:00 UTC, marrobi requested changes
One question, couple of find replace errors, thanks for looking into this.

2024-01-16 15:00 UTC, marrobi commented on templates/workspaces/airlock-import-review/Dockerfile.tmpl
> +# Copy all files FROM --platform=linux/amd64 base workspace (note: some of them will be overwritten with the following COPY command)
Think find and replace went wrong.

2024-01-16 15:08 UTC, m1p1h commented on devops/scripts/bundle_runtime_image_build.sh
> +ARCHITECTURE=$(docker info --format "{{ .Architecture }}" )
The only reason I put this in was because the images will build quicker if buildx isn't needed locally. But I dont have a strong view either way.

2024-01-16 15:13 UTC, marrobi commented on devops/scripts/bundle_runtime_image_build.sh
> +ARCHITECTURE=$(docker info --format "{{ .Architecture }}" )
So on what platform is `aarch64` retuned?

2024-01-16 15:14 UTC, m1p1h commented on templates/workspaces/airlock-import-review/Dockerfile.tmpl
> +# Copy all files FROM --platform=linux/amd64 base workspace (note: some of them will be overwritten with the following COPY command)
fixed

2024-01-16 15:18 UTC, m1p1h commented on devops/scripts/bundle_runtime_image_build.sh
> +ARCHITECTURE=$(docker info --format "{{ .Architecture }}" )
aarch64 and arm64 refer to the same thing aka arm chipsets e.g. apple M1/M2

2024-01-16 19:25 UTC, marrobi commented
/test-extended

2024-01-17 13:12 UTC, marrobi commented
@m1p1h happy for you to add the ignore to `.github/linters/.hadolint.yaml`

2024-01-19 11:16 UTC, m1p1h commented
@marrobi could we rerun the tests

2024-01-19 12:45 UTC, m1p1h commented
sorry - was some trailing white space..should be ok now

2024-01-19 14:02 UTC, marrobi approved these changes
LGTM

2024-01-19 14:02 UTC, marrobi commented
/test-extended 7185718

2024-01-19 14:45 UTC, marrobi commented
@m1p1h actually, missed, can you add an update to the changelog, just a simple one liner with reference the the PR.

An unrelated dependency issue seems to have raised it's head. I'll try fix that while you update the changelog. Thanks.

2024-01-19 15:00 UTC, marrobi commented
/test-extended 14dec54

2024-01-19 15:59 UTC, marrobi commented
/test-extended 1f3d4b2

2024-01-19 17:30 UTC, marrobi commented
/test-extended 2d4817d

2024-01-22 15:19 UTC, marrobi commented
/test-destroy-env

2024-01-22 15:49 UTC, marrobi commented
/test-extended

2024-01-22 15:55 UTC, marrobi commented
/test-extended 3ffb74dee

2024-01-22 15:55 UTC, marrobi commented
/test-extended 2d4817d

2024-01-23 09:58 UTC, marrobi commented
/test-extended

2024-01-23 10:03 UTC, marrobi commented
/test-extended bbd19e2

2024-01-23 12:13 UTC, merged

2024-01-23 15:06 UTC, marrobi commented
@m1p1h thanks for the contribution. 

Took a bit of getting merged, weird dependency issue appeared, then our scheduled clean up script deleted the environment I was trying to redeploy to (I didn't realise this was the case), then a duplicate storage account ID which is rare but something we know about!