Sakundu/statestore
microsoft/AzureTRE pull request #55
Opened 2021-05-10 11:00 UTC by sachinkundu

# PR for issue 5292 -> 5480, 5481

## What is being addressed

Add state store to TRE templates
Task: Module integrated with TRE main IaC template
Task IaC template(s) created

## How is this addressed

Add TF for state store cosmosDB
Tables will created later.

Networking for enabling connection to AppServices Management API will be done later.

2021-05-10 15:05 UTC, marrobi requested changes
Can you review the two points. Thanks.

2021-05-10 15:56 UTC, deniscep requested changes
aligned pattern with other modules; all suggestions are interconnected.

2021-05-10 15:56 UTC, deniscep commented on templates/core/terraform/main.tf
> +}
```suggestion
module "state-store" {
  source                = "./state-store"
  resource_name_prefix  = var.resource_name_prefix
  environment           = var.environment
  tre_id                = local.tre_id
  location              = var.location
  resource_group_name   = azurerm_resource_group.core.name
}
```
Suggest changing to the same pattern as the rest of the modules; also solves the naming convention that @marrobi mentioned. To be used together with change to the statestore.tf

2021-05-10 15:56 UTC, deniscep commented on templates/core/terraform/state-store/statestore.tf
> +  name                = var.name
```suggestion
  name                = "cosmos-${var.resource_name_prefix}-${var.environment}-${var.tre_id}"
```

2021-05-10 15:56 UTC, deniscep commented on templates/core/terraform/state-store/variables.tf
> +}
```suggestion
variable "resource_name_prefix" {}
variable "environment" {}
variable "tre_id" {}
variable "location" {}
variable "resource_group_name" {}
```

2021-05-10 15:56 UTC, deniscep commented on templates/core/terraform/state-store/statestore.tf
> +  name                = "tre"
```suggestion
  name                = "cosmos-sql-${var.resource_name_prefix}-${var.environment}-${var.tre_id}"
```

2021-05-11 04:22 UTC, sachinkundu commented on templates/core/terraform/state-store/statestore.tf
> +resource "azurerm_cosmosdb_account" "tre-db-account" {
Let's keep things simple for now. We can go multi region when things work and same with serverless SKU. Premature optimizations is the root of all evil.

2021-05-11 06:37 UTC, marrobi commented on templates/core/terraform/state-store/statestore.tf
> +resource "azurerm_cosmosdb_account" "tre-db-account" {
Can we create an issue to track this down the line. Evaluate appropriate field SKU or similar? @christoferlof

2021-05-11 06:38 UTC, marrobi approved these changes

2021-05-11 07:01 UTC, merged